name: AH Airflow
on: push
jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7

      - name: welcome msg
        run: echo "hello halawa"

      - name: run scriptdragon
        run: chmod +x ./.github/workflows/scriptdragon.sh && ./.github/workflows/scriptdragon.sh